sudo: required
dist: trusty
language: c
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: NODE_ENV=development
#    - os: linux
#      env: CC=clang CXX=clang++ npm_config_clang=1 NODE_ENV=_development
#      compiler: clang
script:
  - echo toothin > tooth.txt
  - echo kajdsj > tooth2.txt
  - echo "-------------------------------"
  - echo $($APPLER)
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "alex"
  - git config --local user.email "alex@protonmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  user: "alexbumbble",
  password: "Foobar123$$"
  file:
    - tooth.txt
    - tooth2.txt
  skip_cleanup: true
  name: "Release for 3.0.9"
  body: "SOmething in body"
env:
  global:
    secure: ALhCcn8gwE00IVJCF5PwB24t8o11V8L+BBtpL9HZvzlmzlH3M+UmVLGK9hfuimdBGLmO8U8aiAuKNrU18JfqkrmIIOQwssrVwr/8zo0r2SOmwcuD80bYYdo0Am8f4M6tdrI+J7TsAPMuJ1vgxg5tdpRwpz+7SEbRMZ+2jTeRvgRTruJ7BKhLEtnr5dD3n4N1t3OvcNju4HJohylH34yWaHE/R6U8zp3Bm1LDNDXXvNUKqLxnuUxBQuUkhXlEj1WssjV9Tj9KHLdsGgDygMOG/1wAWKt/Gs0mAWfP3AlAvkOlPJsD2qALV/VhjDyYNcGKI7kWTQ7b31YYbLmRLsydZ51Ptaiy58tHwgvigBWt6u/EkWNOX5qtCLqGy3WC1N21sd6wPhAMm7rK483RIY4y/ILyai1sHp89ibq6QduypF/TV+aykr/RbzOXUrOEmXW3hwjtQBhtTeOlAmn9hbtLCbtnNTu4iyZ51icrYlsSyHEAaZdBUIOPG6TTAdUO6U+SeGxzz6jkk2niVMvFwWvknapOe0sAaIBmMTyMwjshrMPYHorHU/Y/pbwAhBuxBHDQoaBQfId/XRNlTtmYN51XL9ZGRmycXyYa8tJaW8Co9yBh5BPfX1VKm2XUxiGComFg9yL32CmmozXLffrPheGp9yyNyIORQ2bsxhIuJ0fHEhg=
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
