sudo: required
dist: trusty
language: c
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: NODE_ENV=development
#    - os: linux
#      env: CC=clang CXX=clang++ npm_config_clang=1 NODE_ENV=_development
#      compiler: clang
script:
  - echo $(security)
  - ls ./ 
  - ls /
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
