sudo: required
dist: trusty
language: c
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: NODE_ENV=development
    - os: osx
      osx_image: xcode7.3
      env: NODE_ENV=development
    - os: osx
      osx_image: xcode6.4
      env: NODE_ENV=development
#    - os: linux
#      env: CC=clang CXX=clang++ npm_config_clang=1 NODE_ENV=_development
#      compiler: clang
cache:
  directories:
    - node_modules
    - app/node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
before_deploy:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x ./scripts/shell/import-osx-certs.sh; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ./scripts/shell/import-osx-certs.sh; fi
install:
  - nvm install 10.16.0
  - npm rebuild node-sass --force
  - npm i -g yarn npm@latest snyk
  - export PATH="$PATH:$(yarn global bin)"
  - npm --depth 10 update url-parse
  - yarn add electron-builder@20.34.0
  - yarn global add retire
  - yarn install
before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
    fi
script:
  - npm run compile:database
  - npm run compile
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      npm run retire -- --severity critical --ignorefile .retireignore.json 
    fi
  - npm run dist:mac
  - |
    if [[ "$TRAVIS_OS_NAME" == "darwin" ]]; then
      npm run test
    fi
after_success:
  - npm run triggers:notarization
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
